# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@934047eba531212a2c77e7c1b5999d32c2becb81

    - name: 'Build & Test'
      run: dub build --build=release

    - name: capture build artifacts
      uses: actions/upload-artifact@v4
      with:
          name: Artifacts
          path: .
